### ISSUE TITLE
Trying to help and learn

### ISSUE THREAD

**Issue by rockneurotiko** [LukasKalbertodt/telegram-bot#15]
Hi!

I've been playing with this library learning Rust from a while, and I'm doing some changes and adding new things (all the send* methods for example), I don't know too much Rust, but I know the API so well xD

I just want to let you know that I'm working on it, I don't have good internet until september but I will try to clean my code and do a PR before :smile: 

Thanks for the library =D

**Comment by LukasKalbertodt** [comment]
Sure, new contributions are always welcome. I can't promise to merge them, though. But I'm looking forward to see your PR.

Can you explain what you want to add in those `send*` methods?

**Comment by rockneurotiko** [comment]
Sure, you don't have to merge if it's bad or you don't like it :)

What I mean with `send*` methods are the `sendPhoto`, `sendDocument`, ... of the bot API.

**Comment by LukasKalbertodt** [comment]
Oh right, yes they are still missing. Since we need multipart data for that, please use this crate: https://github.com/cybergeek94/multipart
Should be the best choice I think.

**Comment by rockneurotiko** [comment]
Yeah, I have it already implemented and using that crate, I'll try to do the PR asap :)

Just one question, for implement the methods I'm using a macro (I wanted to learn the macros), but I don't know if use the macro or don't.

**Comment by LukasKalbertodt** [comment]
I don't quite understand, what you're trying to say. Just submit the PR somewhen and I will comment your code then ;)
