### ISSUE TITLE
Add a link to the Telegram bot API reference to README.md

### ISSUE THREAD

**Issue by neuschaefer** [LukasKalbertodt/telegram-bot#3]

**Comment by neuschaefer** [comment]
That will make it easier to check and debug this implementation.

**Comment by neuschaefer** [comment]
After a bit of careful reading, I found that it's here: https://core.telegram.org/bots/api

**Comment by LukasKalbertodt** [comment]
I linked https://core.telegram.org/bots in the README, which itself has a link to the API-doc in the first paragraph. I thought that would be enough...
Furthermore I will add the API link to the rustdoc when writing a proper documentation. But I guess adding the API-Link to the README too is not bad ;)
