### ISSUE TITLE
Decoding Chat::Group(_) fails with Err(EOF)

### ISSUE THREAD

**Issue by neuschaefer** [LukasKalbertodt/telegram-bot#4]
As can be seen with this [test]:
```rust
#[test]
fn decode_groupchat_chat() {
    use Chat;
    let group = r#"{"title":"This is a group chat","id":-12345678}"#;
    let chat: Chat = json::decode(&group).unwrap();
    assert!(chat.is_group());
}
```

[test]: https://github.com/neuschaefer/telegram-bot/blob/tests/src/types/test.rs#L58

I guess `User::decode(d)` consumes the data, so that if it fails, there's nothing left for the second `decode` call to decode.
```rust
impl Decodable for Chat {
    fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error> {
        // If the object can be decoded as User: Return the user. Otherwise
        // try to decode the object as Group.
        match User::decode(d) {
            Ok(user) => Ok(Chat::User(user)),
            Err(_) => Ok(Chat::Group(try!(Decodable::decode(d)))),
        }
    }
}
```

**Comment by LukasKalbertodt** [comment]
Thanks for reporting! Will fix that some when today, I think. Except if you want to fix it, since you're adding tests anyway?

**Comment by neuschaefer** [comment]
I'll let you fix it. Expect a test PR, though.

**Comment by neuschaefer** [comment]
I don't feel like reading `rustc-serialize` docs today :)

**Comment by LukasKalbertodt** [comment]
Fixed.
If you feel like working on tests, you can improve my tests by using raw string literals instead of the escaped stuff I used.
