### ISSUE TITLE
Decoding Vec<Update> of at least two elements fails with MissingFieldError("update_id")

### ISSUE THREAD

**Issue by neuschaefer** [LukasKalbertodt/telegram-bot#8]
This is a weird bug that prevents me from using `telegram-bot`, and I'm not sure whether the bug is here or in `rustc-serialize`. I've added some work-in-progress test [here]. When I remove one of the `Update` blocks in the `decode_vector_of_updates` test, it doesn't fail anymore.

BTW, thanks for writing this library, the code is quite readable.

[here]: https://github.com/neuschaefer/telegram-bot/commit/4d09e0181e36dec1fb91d5aeb34a4c1c5717c73d

**Comment by LukasKalbertodt** [comment]
Nope, my mistake of course. Even a stupid one. Should be fixed now.

> BTW, thanks for writing this library, the code is quite readable.

My pleasure. And thanks für the "readable" comment :-)
